### ISSUE TITLE
这个项目是放弃了吗，现在都3.7了

### ISSUE THREAD

**Issue by Takea3** [Mrmeng-bat/appium--xuexiqiangguo#6]
这个项目是放弃了吗，现在都3.7了

**Comment by Takea3** [comment]
正在打开夜神模拟器
正在打开appium
找到未读文章： 央视快评：永远与人民同呼吸共命运心连心
找到未读文章： “升级版”证券法为资本市场注入澎湃新动力
找到未读文章： 跨越雄关，我们走在大路上——在历史交汇点上开创未来①
找到未读文章： 望海楼：一个流动的中国，充满活力
找到未读文章： “定制服务”让春运更暖心
找到未读文章： 集中力量办大事——坚定我们的制度自信
找到未读文章： 脱贫攻坚让发展成色更足
正在打开 央视快评：永远与人民同呼吸共命运心连心
Traceback (most recent call last):
  File "D:\xuexiqiangguo\appium--xuexiqiangguo-master\学习强国测试.py", line 158, in <module>
    job()
  File "D:\xuexiqiangguo\appium--xuexiqiangguo-master\学习强国测试.py", line 143, in job
    look_text(driver)
  File "D:\xuexiqiangguo\appium--xuexiqiangguo-master\学习强国测试.py", line 99, in look_text
    lists.append(d_text.text)
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\wengp\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: Cached elements 'By.clazz: android.widget.TextView' do not exist in DOM anymore

>>>

**Comment by Takea3** [comment]
还有没办法自动   打开夜神模拟器。。。换了地址的
